name: Metrics embed

on:
  push:
    branches:
      - main  # or your default branch
  schedule:
    - cron: '0 0 * * *'  # optional, runs daily at midnight UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Metrics embed
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
